<?php

$seedersDir = __DIR__ . '/database/seeders';

$files = [
    'SchoolAndUserSeeder' => "<?php\n\nnamespace Database\Seeders;\n\nuse Illuminate\Database\Seeder;\nuse App\Models\School;\nuse App\Models\User;\nuse Illuminate\Support\Facades\Hash;\n\nclass SchoolAndUserSeeder extends Seeder\n{\n    public function run(): void\n    {\n        \$school = School::create([\n            'name' => 'SMK Negeri 1 Indramayu',\n            'npsn' => '20212345',\n            'address' => 'Jl. Jenderal Sudirman No. 1, Indramayu',\n            'phone' => '0234-123456',\n            'email' => 'info@smkn1indramayu.sch.id',\n            'website' => 'https://smkn1indramayu.sch.id',\n            'status' => 'active',\n        ]);\n\n        User::create([\n            'name' => 'Super Administrator',\n            'email' => 'superadmin@lmn.id',\n            'password' => Hash::make('password'),\n            'role' => 'super_admin'\n        ]);\n\n        \$school->users()->create([\n            'name' => 'Admin Sekolah',\n            'email' => 'admin@smk.id',\n            'password' => Hash::make('password'),\n            'role' => 'admin_sekolah'\n        ]);\n\n        \$school->users()->create([\n            'name' => 'Budi Guru RPL',\n            'email' => 'guru@smk.id',\n            'password' => Hash::make('password'),\n            'role' => 'guru'\n        ]);\n\n        \$school->users()->create([\n            'name' => 'Siswa Teladan',\n            'email' => 'siswa@smk.id',\n            'password' => Hash::make('password'),\n            'role' => 'siswa'\n        ]);\n    }\n}\n",

    'AcademicSeeder' => "<?php\n\nnamespace Database\Seeders;\n\nuse Illuminate\Database\Seeder;\nuse App\Models\School;\nuse App\Models\User;\nuse App\Models\AcademicYear;\nuse App\Models\Major;\nuse App\Models\Teacher;\nuse App\Models\Student;\nuse App\Models\Classroom;\nuse App\Models\Subject;\nuse App\Models\Schedule;\n\nclass AcademicSeeder extends Seeder\n{\n    public function run(): void\n    {\n        \$school = School::first();\n        \$guruUser = User::where('role', 'guru')->first();\n        \$siswaUser = User::where('role', 'siswa')->first();\n\n        \$year = AcademicYear::create([\n            'school_id' => \$school->id,\n            'name' => '2023/2024',\n            'semester' => 'Genap',\n            'is_active' => true\n        ]);\n\n        \$majorRpl = Major::create(['school_id' => \$school->id, 'code' => 'RPL', 'name' => 'Rekayasa Perangkat Lunak']);\n        Major::create(['school_id' => \$school->id, 'code' => 'TKJ', 'name' => 'Teknik Komputer Jaringan']);\n\n        \$teacher = Teacher::create([\n            'user_id' => \$guruUser->id,\n            'school_id' => \$school->id,\n            'nip' => '198001012005011003',\n            'gender' => 'L',\n        ]);\n\n        \$classroom = Classroom::create([\n            'school_id' => \$school->id,\n            'major_id' => \$majorRpl->id,\n            'academic_year_id' => \$year->id,\n            'homeroom_teacher_id' => \$teacher->id,\n            'level' => 10,\n            'name' => 'X RPL 1'\n        ]);\n\n        \$student = Student::create([\n            'user_id' => \$siswaUser->id,\n            'school_id' => \$school->id,\n            'major_id' => \$majorRpl->id,\n            'classroom_id' => \$classroom->id,\n            'nis' => '102938',\n            'gender' => 'L'\n        ]);\n\n        \$subject = Subject::create([\n            'school_id' => \$school->id,\n            'major_id' => \$majorRpl->id,\n            'code' => 'PBO',\n            'name' => 'Pemrograman Berorientasi Objek'\n        ]);\n\n        Schedule::create([\n            'school_id' => \$school->id,\n            'academic_year_id' => \$year->id,\n            'classroom_id' => \$classroom->id,\n            'subject_id' => \$subject->id,\n            'teacher_id' => \$teacher->id,\n            'day_of_week' => 1, // Senin\n            'start_time' => '07:00:00',\n            'end_time' => '09:00:00'\n        ]);\n    }\n}\n",

    'CbtSeeder' => "<?php\n\nnamespace Database\Seeders;\n\nuse Illuminate\Database\Seeder;\nuse App\Models\School;\nuse App\Models\Teacher;\nuse App\Models\Subject;\nuse App\Models\Classroom;\nuse App\Models\Exam;\nuse App\Models\Question;\nuse App\Models\QuestionOption;\nuse Carbon\Carbon;\n\nclass CbtSeeder extends Seeder\n{\n    public function run(): void\n    {\n        \$school = School::first();\n        \$teacher = Teacher::first();\n        \$subject = Subject::first();\n        \$classroom = Classroom::first();\n\n        \$exam = Exam::create([\n            'school_id' => \$school->id,\n            'teacher_id' => \$teacher->id,\n            'subject_id' => \$subject->id,\n            'title' => 'Ujian Tengah Semester PBO',\n            'description' => 'Kerjakan dengan jujur. Waktu 60 menit.',\n            'start_time' => Carbon::now()->subMinutes(10),\n            'end_time' => Carbon::now()->addHours(2),\n            'duration_minutes' => 60,\n            'type' => 'uts'\n        ]);\n\n        \$exam->classrooms()->attach(\$classroom->id);\n\n        \$q1 = Question::create(['exam_id' => \$exam->id, 'type' => 'multiple_choice', 'text' => 'Apa paradigma utama bahasa Java?']);\n        QuestionOption::create(['question_id' => \$q1->id, 'text' => 'Procedural']);\n        QuestionOption::create(['question_id' => \$q1->id, 'text' => 'Functional']);\n        QuestionOption::create(['question_id' => \$q1->id, 'text' => 'Object Oriented', 'is_correct' => true]);\n\n        Question::create(['exam_id' => \$exam->id, 'type' => 'essay', 'text' => 'Jelaskan perbedaan Inheritance dan Polymorphism!']);\n    }\n}\n",

    'FeatureSeeder' => "<?php\n\nnamespace Database\Seeders;\n\nuse Illuminate\Database\Seeder;\nuse App\Models\School;\nuse App\Models\Student;\nuse App\Models\MyfessPost;\n\nclass FeatureSeeder extends Seeder\n{\n    public function run(): void\n    {\n        \$school = School::first();\n        \$student = Student::first();\n\n        MyfessPost::create([\n            'school_id' => \$school->id,\n            'student_id' => \$student->id,\n            'content' => 'Gimana sih cara ngoding yang gak bikin pusing? #help',\n            'is_anonymous' => true,\n            'status' => 'published'\n        ]);\n    }\n}\n",

    'DatabaseSeeder' => "<?php\n\nnamespace Database\Seeders;\n\nuse Illuminate\Database\Seeder;\n\nclass DatabaseSeeder extends Seeder\n{\n    public function run(): void\n    {\n        \$this->call([\n            SchoolAndUserSeeder::class,\n            AcademicSeeder::class,\n            CbtSeeder::class,\n            FeatureSeeder::class,\n        ]);\n\n        \$this->command->info('==== LMN SEEDING SUCCESS ====');\n        \$this->command->info('Super Admin: superadmin@lmn.id');\n        \$this->command->info('Admin Sekolah: admin@smk.id');\n        \$this->command->info('Guru: guru@smk.id');\n        \$this->command->info('Siswa: siswa@smk.id');\n        \$this->command->info('Global Password: password');\n    }\n}\n"
];

foreach ($files as $name => $content) {
    file_put_contents($seedersDir . '/' . $name . '.php', $content);
}

echo "Seeders split modularly successfully!";
